# Docker Setup Workflow Configuration
name: setup-docker
description: "Setup Docker development environment for Next.js prototyping with hot-reload and volume mounting"
author: "Fede"

# Critical variables load from config_source
config_source: "{project-root}/bmad/rapid-proto/config.yaml"
user_name: "{config_source}:user_name"
tech_stack: "{config_source}:tech_stack"
date: system-generated

# Module path and component files
installed_path: "{project-root}/bmad/rapid-proto/workflows/setup-docker"
template: false # Action workflow - no template document
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Docker templates
docker_templates: "{installed_path}/templates/"

# Target project configuration
target_project_path: "{{user_project_path}}" # User specifies project location
project_name: "{{project_name}}" # User provides project name

# Docker configuration
docker_config:
  node_version: "20-alpine"
  port: 3000
  work_dir: "/app"

# Execution mode
mode: "{{mode}}" # 'setup' (default) or 'verify' (check existing setup)

standalone: true
