# Create Page Workflow Configuration
name: create-page
description: "Build a new Next.js 16 page with App Router, routing, layout, and metadata"
author: "Fede"

# Critical variables load from config_source
config_source: "{project-root}/bmad/rapid-proto/config.yaml"
module_root: "{config_source}:module_root"

# Context system for tracking
context_docs_path: "{project-root}/docs/rapid-prototype"
build_log: "{context_docs_path}/build-log.md"

# Module path and component files
installed_path: "{project-root}/bmad/rapid-proto/workflows/create-page"
template: false # Action workflow - no template document
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Page configuration
page_types:
  - static # Static page
  - dynamic # Dynamic route with params
  - layout # Layout component

# Default paths in target project
target_project_root: "{{project_root}}" # Where the prototype lives
app_path: "{{project_root}}/app"

standalone: true
