# Review Code Workflow Configuration
name: review-code
description: "Systematic code review for best practices, type safety, performance, and quality"
author: "Fede"

# Critical variables load from config_source
config_source: "{project-root}/bmad/rapid-proto/config.yaml"
module_root: "{config_source}:module_root"

# Context system for tracking
context_docs_path: "{project-root}/docs/rapid-prototype"
build_log: "{context_docs_path}/build-log.md"
refactor_log: "{context_docs_path}/refactor-log.md"

# Module path and component files
installed_path: "{project-root}/bmad/rapid-proto/workflows/review-code"
template: false # Action workflow - no template document
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Review scope options
review_scope:
  - recent # Recent changes from build log
  - full # Full project review
  - specific # Specific files or components

standalone: true
